### ISSUE TITLE
face detection broken on colab pytorch 1.8 cuda 11

### ISSUE THREAD

**Issue by eyaler** [Rudrabha/Wav2Lip#231]
colab has recently updated to pytorch 1.8 + cuda 11 and face_detection breaks with oom / cuda errors. i am not sure exactly why but i was able to fix by adding `.copy()` to `from_numpy()` in `detect()`, `batch_detect()` as done in the original repo here: https://github.com/1adrianb/face-alignment/commit/88cc1dfa41b02b3021bbfa26b30ed8859e2d4290. you can see my fix here: https://github.com/eyaler/Wav2Lip/commit/fd29d6e8d432a823bd7fd0fd99c2ebff323df979
```
Recovering from OOM error; New batch size: 8

  0% 0/1 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 4

  0% 0/1 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 2

  0% 0/1 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 1

  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 78, in face_detect
    predictions.extend(detector.get_detections_for_batch(np.array(images[i:i + batch_size])))
  File "/content/Wav2Lip/face_detection/api.py", line 66, in get_detections_for_batch
    detected_faces = self.face_detector.detect_from_batch(images.copy())
  File "/content/Wav2Lip/face_detection/detection/sfd/sfd_detector.py", line 42, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, images, device=self.device)
  File "/content/Wav2Lip/face_detection/detection/sfd/detect.py", line 68, in batch_detect
    imgs = torch.from_numpy(imgs).to(device, dtype=torch.float32)
RuntimeError: CUDA error: an illegal memory access was encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 292, in <module>
    main()
  File "inference.py", line 262, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "inference.py", line 127, in datagen
    face_det_results, _ = face_detect([frames[0]])
  File "inference.py", line 81, in face_detect
    raise RuntimeError('Image too big to run face detection on GPU. Please use the --resize_factor argument')
RuntimeError: Image too big to run face detection on GPU. Please use the --resize_factor argument
```

**Comment by codehearted** [comment]
Thank you! Your changes fixed this same issue for me with Cuda 11.1.

**Comment by i-amgeek** [comment]
Thanks @eyaler. It worked.

**Comment by wuwenjie1992** [comment]
tank you 谢谢

**Comment by JunjieLl** [comment]
Thank you very much!

**Comment by YuanSnowing** [comment]
Thank you very much!

**Comment by troy0632** [comment]
how to fixed it , I see around can not found anythings about answer

**Comment by eyaler** [comment]
my notebook still works. what error are you seeing and with what settings and media?

**Comment by georgezouq** [comment]
still this error

**Comment by eyaler** [comment]
> still this error

@georgezouq can you confirm if you are using the original notebook or my [fixed notebook](https://j.mp/wav2lip)?

**Comment by jiuang** [comment]
> I tried , but still this error

> still this error

@troy0632 @georgezouq hi, guys, please notice the compatibility for torch and cuda. The default torch's version may be a little low.
![image](https://github.com/Rudrabha/Wav2Lip/assets/34175244/eb967fee-b88e-4c13-8e9e-6913024dff10)

**I upgraded to python3.8 and torch2.1.2, then it worked. Hope it helps.**

![image](https://github.com/Rudrabha/Wav2Lip/assets/34175244/9d952899-6289-46ab-9f7c-aada548ec6dd)

**Comment by QQbbla** [comment]
> > I tried , but still this error
> 
> > still this error
> 
> [@troy0632](https://github.com/troy0632) [@georgezouq](https://github.com/georgezouq) hi, guys, please notice the compatibility for torch and cuda. The default torch's version may be a little low. ![image](https://github.com/Rudrabha/Wav2Lip/assets/34175244/eb967fee-b88e-4c13-8e9e-6913024dff10)
> 
> **I upgraded to python3.8 and torch2.1.2, then it worked. Hope it helps.**
> 
> ![image](https://github.com/Rudrabha/Wav2Lip/assets/34175244/9d952899-6289-46ab-9f7c-aada548ec6dd)

pretty good
