### ISSUE TITLE
Question : apple silicon compatibility ?

### ISSUE THREAD

**Issue by x4080** [Rudrabha/Wav2Lip#561]
Hi, can I use this with apple silicon ?

Thanks

**Comment by ediaStudio** [comment]
Hi, i use it with M1 and it's working like a charm
librosa==0.9.1
numpy==1.26.1
opencv-contrib-python==4.8.1.78
opencv-python==4.8.1.78
torch==2.1.0
torchvision==0.16.0
tqdm==4.66.1
numba==0.58.1

**Comment by x4080** [comment]
@ediaStudio Thanks, I'll try your suggestion

**Comment by x4080** [comment]
@ediaStudio Thanks, it works after some modification

**Comment by jlindsay** [comment]
Hello, I keep getting the following error...  saying AssertionError: Torch not compiled with CUDA enabled ....

Any help would be appreciated. 

Traceback (most recent call last):
  File "/Users/jlindsay/dev/Wav2Lip/preprocess.py", line 95, in mp_handler
    process_video_file(vfile, args, gpu_id)
  File "/Users/jlindsay/dev/Wav2Lip/preprocess.py", line 65, in process_video_file
    preds = fa[gpu_id].get_detections_for_batch(np.asarray(fb))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlindsay/dev/Wav2Lip/face_detection/api.py", line 66, in get_detections_for_batch
    detected_faces = self.face_detector.detect_from_batch(images.copy())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlindsay/dev/Wav2Lip/face_detection/detection/sfd/sfd_detector.py", line 45, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, images, device=self.device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlindsay/dev/Wav2Lip/face_detection/detection/sfd/detect.py", line 65, in batch_detect
    imgs = torch.from_numpy(imgs).float().to(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlindsay/opt/miniconda3/envs/wav2lip/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:53<00:00, 53.71s/it]
Dumping audios...
  0%|
